### ISSUE TITLE
Add Trac exports via `tractive`

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#18]
## xml2rfc

* Trac: xml2rfc instance, filter: component = anything except `v3 vocabulary`
* SVN: ietf-ribose/xml2rfc

## xml2rfc-website

* Trac: xml2rfc instance, filter: (TODO)
* SVN: ietf-ribose/xml2rfc-website

## xml2rfc-bibxml

* Trac: xml2rfc instance, filter: (TODO)
* SVN: ietf-ribose/xml2rfc-bibxml

## vocabulary_design_team_2013_2017

* Trac: xml2rfc instance, filter: component = `v3 vocabulary`
* SVN: ietf-ribose/vocabulary_design_team_2013_2017

The Trac tickets for the "vocabulary_design_team_2013_2017" repo can be seen here
https://trac.ietf.org/trac/xml2rfc/query

<img width="272" alt="Screenshot 2021-09-25 at 9 46 30 AM" src="https://user-images.githubusercontent.com/11865/134753791-4156581b-f38e-4bf1-8d0f-90cc2b67107e.png">

_(originally from https://github.com/ietf-ribose/svn-github-convert/issues/7#issuecomment-926992804)_

## ietfdb (Datatracker)

* Trac: ietfdb instance, filter: component = `Datatracker: *` (see screenshot)
* SVN: ietf-ribose/ietfdb

<img width="172" alt="Screenshot 2021-09-23 at 4 12 47 PM" src="https://user-images.githubusercontent.com/11865/134474464-4d7695b3-42a7-452f-b617-3e79c1760638.png">

## ietfdb (Mailarchive)

* Trac: ietfdb instance, filter: component = `MailArchive: *` (see screenshot)
* SVN: ietf-ribose/mailarch

<img width="184" alt="Screenshot 2021-09-23 at 4 16 29 PM" src="https://user-images.githubusercontent.com/11865/134474996-04b5c495-5446-4fa7-a7d2-562c3bbdb5b2.png">

## Mailreplay

No Trac, no need to migrate issues.

## Postconfirm

No Trac, no need to migrate issues.

## Postfind

No Trac, no need to migrate issues.

## dmarc

Trac: trac-svn-db/trac/dmarc
SVN: none.

## emailcore

Trac: trac-svn-db/trac/emailcore
SVN: none.

## tsvwg

Trac: trac-svn-db/trac/tsvwg
SVN: none.

**Comment by ronaldtse** [comment]
Remaining: mailreplay, postconfirm, postfind, dmarc, emailcore, tsvwg.

**Comment by ronaldtse** [comment]
@rjsparks for the new `ietfdb` repository, can we confirm that all Trac tickets that relate to components other than `MailArchive: *` should be migrated there? Thanks.

<img width="199" alt="Screenshot 2021-09-28 at 9 39 13 AM" src="https://user-images.githubusercontent.com/11865/135008200-7ca7585d-7892-4aef-976b-3f87fca926b0.png">

**Comment by ronaldtse** [comment]
I have added a new GitHub organization called `ietf-svn-conversion` (https://github.com/ietf-svn-conversion) for the testing of migrating issues. All users have full admin rights there so that you can delete/re-create the repos there when a re-run is necessary.

**Comment by HassanAkbar** [comment]
@ronaldtse What should the filters be in case of `xml2rfc-website` and `xml2rfc-bibxml` ?
<img width="253" alt="Screen Shot 2021-10-11 at 2 46 26 PM" src="https://user-images.githubusercontent.com/5301572/136769760-f2c2a732-6c92-4765-a581-3077d4a1c096.png">

**Comment by ronaldtse** [comment]
I've provided a structure here: https://github.com/ietf-ribose/svn-github-convert/blob/main/github-users-email.yaml . 

We have to do this manually.

**Comment by HassanAkbar** [comment]
> I've made a new issue for this: #35 . Tractive needs to utilize this new mapping format for GitHub email => username.

Sure thing. I will take over this after getting the Github workflow finalized.

**Comment by HassanAkbar** [comment]
> I've made a new issue for this: #35 . Tractive needs to utilize this new mapping format for GitHub email => username.

Just to clarify, are we changing the format of user mapping provided to tractive in the [`config.yaml`](https://github.com/ietf-ribose/tractive/blob/03af51984d20ff1923630290b6a97422853f578c/config.example.yaml#L26) file from 
```yaml 
adam@nostrum.com: adamroach
```
 to 
```yaml
mapping:
  - name: Adam Roach
    email: adam@nostrum.com
    username: adamroach
```

@ronaldtse I just wanted to know if there is a special reason for that because hash will give us O(1) for retrieval while the new format (of the array) will take O(N) for retrieval.

**Comment by ronaldtse** [comment]
Yes, the reason is we want to keep the name, email and username together for information purposes. 

There should be no performance difference here because we should read the entire file at once in the beginning, then we can convert this into a hash internally. A big-O difference only happens if we’re using this structure to search, but we’re not (I.e. file data representation != data representation in Tractive).

**Comment by ronaldtse** [comment]
@HassanAkbar there is a misunderstanding: 
> It feels like reposurgeon is creating usernames for commits by stripping everything in the email address after the @ symbol.

Perhaps the list in the screenshot is outdated? In the current repo, we no longer have the `reposurgeon` names. We have changed them all to real names:
https://github.com/ietf-ribose/svn-github-convert/search?q=tom111

<img width="748" alt="Screenshot 2021-10-14 at 7 41 06 PM" src="https://user-images.githubusercontent.com/11865/137310728-e7eb7488-2972-499c-ba10-77389252225a.png">

We obtained all these emails from an IETF internal system, the emails are *correct*. However, the emails are not necessarily mapped to a GitHub-registered email, and that user may not have a GitHub account.

This is the list of emails not yet mapped to a GitHub account:
* https://github.com/ietf-ribose/svn-github-convert/issues/21#issuecomment-930782970

So in order to make the mapping happen we really need to finalise the SVN user to GitHub email/username mapping.

**Comment by rjsparks** [comment]
No - it's fine (maybe a feature) if ticket assignment gets lost.
@rpcross, @jennifer-richards, @kesara: heads up...

**Comment by ronaldtse** [comment]
@rjsparks so just to confirm that we "won't migrate ticket assignments" but keep them in the issue comments as text.

By any chance @rpcross is the elusive Ryan Cross we've trying to pin down? Would he be able to add his `amsl.com` email to his GitHub account to enable linking?

**Comment by HassanAkbar** [comment]
@ronaldtse As we will be creating all issues from one Github account. 
We will be needing the `Github  Personal Access Token` of the user we want to use for final migration.

**Comment by ronaldtse** [comment]
Thanks for checking. I don’t remember what the other components are other than Datatracker. Do you have a list?

**Comment by HassanAkbar** [comment]
@ronaldtse 

1. For changing `SVN revision` to `GIT SHA` in the commit messages, we need to create new commits because commits are immutable in Git. We can only `Remove & REDO` to change an existing commit message.
2. Each commit after `REMOVE & REDO` will have new `SHA`, so we will have to update the `revmap` file after updating each commit message.
3. We can not do this in `reposurgeon` because it creates a fast-import stream for git to create the repo. Before importing that file to Github, we don't have the `SHA` hashes. So, we can only edit commit messages after the import of Github repo.
4.  I am investigating if [git-filter-repo](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html) tool can edit the commit message without affecting Tree of commits.


Let me know if you have any other thoughts here.

**Comment by ronaldtse** [comment]
@HassanAkbar thank you for researching the approach. 

1. I think first of all let's find whether the IETF repos do contain those revision references. If the commit messages do not contain revision references, then we don't need to migrate them.
2. If there are revision references, we will want to consider the volume of them.
3. In addition I think it may be possible to do it "during" reposurgeon conversion in the '.lift' file. 

Can you help check step 1? Thanks!

**Comment by HassanAkbar** [comment]
@ronaldtse 
1. Yes the commit messages do contain references to the revisions, e.g.
   <img width="1202" alt="Screenshot 2021-11-04 at 2 07 57 PM" src="https://user-images.githubusercontent.com/5301572/140287054-01389b85-c55e-45f0-a29c-7ec9d9fe9b7c.png">
2. There are about 1500 references like above in `ietfdb` only.
3. From what I understand we can [change the references](http://www.catb.org/~esr/reposurgeon/repository-editing.html#reference-lifting) like `[[SVN:XXXX]]` into `timestamps` in `.lift` file, but I didn't find a way in reposurgeon to change them into `Git commit SHA hashes`.

**Comment by ronaldtse** [comment]
It's hard to say whether it is better or worse to replace them with a Git commit. Perhaps instead of "replace" we should "add a Git commit hash" to the commit message. In this case it means that we will need to post process and perhaps add a commit has at the end of the original message.

However that means we need to update our rev map.

**Comment by ronaldtse** [comment]
@HassanAkbar is now trying to achieve a solution.

I'm still not sure how we can deal with this outside `reposurgeon`:

1. The `git filter-branch` command which we want to use to re-build the commits (to add the commit hash) will create new commits with new hashes
2. Then the re-written commits will not have the correct reference Git commit hashes.

`reposurgeon` only allows replacing the SVN revision with an "action stamp", which is of the pattern "username@timestamp", and we know that these stamps are ambiguous because multiple commits can be created at the same time (we see that in ietfdb).

According to this page (https://stackoverflow.com/questions/5212957/how-to-change-git-commit-message-without-changing-commit-hash), the only possibility is using `git notes`.

And GitHub discontinued Git notes support in 2014: https://github.blog/2010-08-25-git-notes-display/

**Comment by ronaldtse** [comment]
It is possible to add a legacy message to every commit:
* https://gitlab.com/esr/reposurgeon/-/issues/186

`reposurgeon` documentation strongly discourages using commit hashes in messages:
http://www.catb.org/~esr/reposurgeon/repository-editing.html#_step_six_good_practice

> 4.9. Step Six: Good Practice
> Educate your developers in the following good practices:
> 
> 4.9.1. Commit references
> The combination of a committer email address with a ISO8601 timestamp is a good way to refer to a commit without being VCS-specific. Thus, instead of "commit 304a53c2", use "<2011-10-25T15:11:09Z!fred@foonly.com>". It is recommended that you not vary from this format, even in trivial ways like omitting the 'Z' or changing the 'T' or '!'. Making these cookies uniform and machine-parseable will have good consequences for future repository-browsing tools. The reference-lifting code in reposurgeon generates them.
> 
> Being careful about this has an additional benefit. Someday your project may need to change VCSes yet again; on that day, it will be extremely helpful if nobody has to try to convert years' or decades' worth of VCS-specific magic cookies in the history.
> 
> Sometimes it’s enough to quote the summary line of a commit. So, instead of "Back out most of commit 304a53c2", you might write "Back out Attempted divide-by-zero fix."

As "action stamps" can be ambiguous, reposurgeon actually provides a way around this, via ["timequakes"](http://www.catb.org/~esr/reposurgeon/repository-editing.html#timequakes):
> Modifying a repository so every commit in it has a unique timestamp is often a useful thing to do, in order for every commit to have a unique action stamp that can be referred to in surgical commands.

**Comment by ronaldtse** [comment]
In order to lift references from the SVN commit messages, this is an example from reposurgeon documentation:

This command rewrites the SVN r23 revision message (via `Legacy-ID: 23`) to include a revision number. We can apply this command for all revisions to update, not sure if there's a more "batch" manner.

```
# This command illustrates how to use msgin to modify the comment
# text of a commit. In this test we're patching a Subversion revision
# reference because we're going to want to reference-lift it later.
# But this capability could also be used, for example, to add an
# update note to a commit comment that turned out to be incorrect.
msgin <<EOF
Legacy-ID: 23
Check-Text: Referring back to r2.

Referring back to [[SVN:2]].
EOF
```

It is also possible to append messages to converted commits, via Legacy-ID:
```
SELECTION append [--rstrip] [--legacy] TEXT
Append text to the comments of commits and tags in the specified selection set. The text is the first token of the command and may be a quoted string. C-style escape sequences in the string are interpreted using Go’s Quote/Unquote codec from the strconv library.

If the option --rstrip is given, the comment is right-stripped before the new text is appended. If the option --legacy is given, the string %LEGACY% in the append payload is replaced with the commit’s lagacy-ID before it is appended.

Sets Q bits: true for each commit and tag modified, false otherwise.

Example:

=C append "\nLegacy-Id: %LEGACY%" --legacy
```

**Comment by HassanAkbar** [comment]
@ronaldtse 
We can append `Legacy-ID` or `timestamp` to the commit message using reposurgeon, but if we want to add a `Git Commit SHA` we will have to use a post-processing tool like `git-filter-repo`.

1. If we want to use reposurgeon, the searching will be a manual process:
   - Append `legacy-ID` to each commit message. This `legacy-ID` is actually `SVN Revision Number`.
   - For example, a commit message is `Merged in [1234]`.
   - User wants to view commit against `SVN Revision: 1234`.
   - User can do a search in Github by using `Legacy-ID: 1234`.
   -  <img width="852" alt="Screenshot 2021-11-08 at 8 23 57 PM" src="https://user-images.githubusercontent.com/5301572/140769398-c4e4ac5e-16f3-46c6-bc4f-4b1c032fe944.png">
    

2. Using `git-filter-repo` is a risky approach(so, I need to confirm all cases here). Using it we can add a link to the related repo in the commit message. This makes process seamless for the user.
   - User will be able to see a link appended to every commit like [this commit](https://github.com/hassanakbar4/ietfdb/commit/fb1bf8b6cb4906179fda31354934d73a9e06e54b)
   - <img width="1227" alt="Screenshot 2021-11-08 at 8 36 42 PM" src="https://user-images.githubusercontent.com/5301572/140771552-5b4dcfc8-a3d4-4398-a2f9-36bc5aff16ea.png">

**Comment by ronaldtse** [comment]
I think 1 is an acceptable alternative.

My question for 2 is whether it is even possible. Because `git-filter-repo` will rewrite the commits, so if we enter say `fb1bf8b` into the commit, the commit will already be rewritten away.

Technically, if we rewrite the commits in the original order then only the new ones get updated. However I'm not sure if we can enforce this order when running `git-filter-repo`. And notice that we need to rewrite all downstream commits if we change a single commit. I am not sure if this is actually possible.

**Comment by HassanAkbar** [comment]
@ronaldtse Yes, I agree the first approach is simple and less error-prone,

As for 2, according to the [documentation of git-filter-repo](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#FRESHCLONE), we can add a commit SHA in message and if while rewriting a reference to an old commit SHA is found it is updated to the new SHA.

> By default, since commits are rewritten and thus gain new hashes, references to old commit hashes in commit messages are replaced with new commit hashes (abbreviated to the same length as the old reference).

But I haven't tested this out.

**Comment by ronaldtse** [comment]
@HassanAkbar wow! `git-filter-repo` **IS** the answer.

> Additionally, several concerns are handled automatically (many of these can be overridden, but they are all on by default):
>
> * rewriting (possibly abbreviated) hashes in commit messages to refer to the new post-rewrite commit hashes

Yes let's do this! If `git-filter-repo`'s documentation isn't lying, 2 will work!

**Comment by HassanAkbar** [comment]
@ronaldtse I ran `git-filter-repo` on this [test repo](https://github.com/hassanakbar4/ietfdb-git). I am trying verify if everything seems good. Can you also take a look at it ?

Note: There is a SHA added in some commits after `Legacy-ID: <id>`, ignore that, It was added while testing and will not exist in the final migration.
<img width="1231" alt="Screenshot 2021-11-09 at 8 10 22 PM" src="https://user-images.githubusercontent.com/5301572/140950337-9426bd0d-f11e-4937-a2e7-e6b672326813.png">

**Comment by ronaldtse** [comment]
@HassanAkbar I'm looking at the same commit and the one it refers to:

https://github.com/hassanakbar4/ietfdb-git/commit/b899ee18604e878fb4133ef38cfeb6af781ce116
<img width="1232" alt="Screenshot 2021-11-10 at 5 49 45 PM" src="https://user-images.githubusercontent.com/11865/141090441-41235f42-256c-4e6b-874d-7fdda5cd6bcf.png">

https://github.com/hassanakbar4/ietfdb-git/commit/521f141d6b0c3104c21b9af03dfe58a0c8e5b018
<img width="1236" alt="Screenshot 2021-11-10 at 5 52 38 PM" src="https://user-images.githubusercontent.com/11865/141090905-eec5f273-c9dd-410b-96ad-34d8b54a5e75.png">

The first commit corresponds to SVN 19397 and the second to SVN 19396.

In the commit message of the first, just having "521f141" is not clear.

How about we point out in the message, e.g
* NOTE: "SVN reference [19396] has been migrated to Git commit 521f141"

?

**Comment by HassanAkbar** [comment]
@ronaldtse Agreed this would be better.

One more thing, what should we do in case of multiple SVN references, i.e https://github.com/ietf-ribose/ietfdb/commit/e62c503e294934323027ad56128c4421b019e1af?

I thing we can do one of the following:
1. SVN reference [1234], [5678] has been migrated to Git commit 521f141, 77fe998e respectively
2. SVN references
    - [1234] -> 521f141
    - [5678] -> 77fe998e

**Comment by ronaldtse** [comment]
Multiple lines of this would already be sufficient, no need to be too fancy.

```
NOTE: SVN reference [19396] has been migrated to Git commit 1111111
NOTE: SVN reference [19397] has been migrated to Git commit 2222222
```

**Comment by rjsparks** [comment]
I agree, but to test the edges, consider https://trac.ietf.org/trac/ietfdb/changeset/19596/trunk

**Comment by ronaldtse** [comment]
Thanks @rjsparks . The migrated commit can be seen here right now: https://github.com/ietf-ribose/ietfdb/commit/f81f1bf2c4ad82f3d4907d8654e7f2b5e300c253 Indeed it is worth checking... 🙀

**Comment by HassanAkbar** [comment]
@ronaldtse Here is the repo after changing the commit message: [hassanakbar4/ietfdb-filter-repo-test](https://github.com/hassanakbar4/ietfdb-filter-repo-test/tree/main). And here is the commit mentioned by rjsparks: https://github.com/hassanakbar4/ietfdb-filter-repo-test/commit/02fa573c26bab915cca98f1f222adba3ade88fec

**Comment by ronaldtse** [comment]
@rjsparks could you help verify that the conversion here makes sense? Thanks.

https://github.com/hassanakbar4/ietfdb-filter-repo-test/commit/02fa573c26bab915cca98f1f222adba3ade88fec

**Comment by ronaldtse** [comment]
Closing in favour of #43 and #44. Thanks all!
