### ISSUE TITLE
During SVN-Git conversion, update commit messages to refer to the converted Git commits

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#19]
`reposurgeon` has the ability to "lift references" (http://www.catb.org/~esr/reposurgeon/repository-editing.html#reference-lifting)

What I'm not sure about is how to use this functionality to edit the resulting Git commits within `reposurgeon` so that it is a one step conversion.

This will likely require updating of the `*.lift` files (per converted repo) in this repository.

@HassanAkbar could you help investigate? Thanks!

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/tractive/issues/10#issuecomment-927870523_

**Comment by ronaldtse** [comment]
Added 5951654a3185824244cc2ef5da32fb8198093352 to push to a new SVN-Git map repository, https://github.com/ietf-ribose/svn-git-maps .

**Comment by HassanAkbar** [comment]
@ronaldtse 
There are some [duplicates](https://github.com/ietf-ribose/svn-git-maps/blob/cf7545664841fcf0c3f7fcfced4a7915b6e74379/ietfdb.fo#L1447) in the map file i.e There are multiple commits of a single user at the same timestamp. There are almost 150 duplicates in the [ietfdb file](https://github.com/ietf-ribose/svn-git-maps/blob/main/ietfdb.fo) alone.

What do you suggest, how should we deal with them? Should we ask the user to resolve them manually?

**Comment by ronaldtse** [comment]
@HassanAkbar how can there be multiple commits of a single user at the same revision?

**Comment by ronaldtse** [comment]
For example,
https://github.com/ietf-ribose/svn-git-maps/blob/cf7545664841fcf0c3f7fcfced4a7915b6e74379/ietfdb.fo#L1446-L1450

The first three lines have the same SVN revision appended by a period and a separate number. Could you help check what that means?

**Comment by HassanAkbar** [comment]
> For example,
> https://github.com/ietf-ribose/svn-git-maps/blob/cf7545664841fcf0c3f7fcfced4a7915b6e74379/ietfdb.fo#L1446-L1450
> 
> The first three lines have the same SVN revision appended by a period and a separate number. Could you help check what that means?

@ronaldtse Sorry, you are right. I gave you the wrong example. I will get back to you on this.


Secondly, Postfind has [different revision numbers ](https://github.com/ietf-ribose/svn-git-maps/blob/main/postfind.fo#L10) with the same user and the same timestamp.

**Comment by HassanAkbar** [comment]
@ronaldtse can you also upload the `ietfdb` repo to git or the `.svn` file in svn-git-converter?
I was able to visualize what's happening on the svn side but really want to correlate it to git.

I want to understand what is happening on GitHub when there are entries that are appended by a dot and a number, So the git repo can help a lot.

**Comment by ronaldtse** [comment]
@HassanAkbar the git repo is pushed daily to ietf-ribose/ietfdb, and if you want the .svn file you can clone this current repo, go to the ietfdb folder and run “make”. (You will need to use your GH token to download the SVN repo from trac-svn-db, then link the SVN repo to ietfdb/ietfdb-mirror).

**Comment by ronaldtse** [comment]
@HassanAkbar can you confirm you can reproduce the SVN-Git conversion steps locally?

Steps to run locally:
1. Clone this repo, e.g. to `./svn-github-convert`
2. Clone the https://github.com/ietf-ribose/trac-svn-db/ repo to a level up, e.g. `./trac-svn-db` (remember this is a private repo)
3. Change directory to the target repo name, e.g. `./svn-github-convert/xml2rfc-bibxml`
4. Within this directory run `ln -s ../../trac-svn-db/svn/xml2rfc xml2rfc-bibxml-mirror` (notice that the `xml2rfc-*` and `vocabulary...` target repositories are all created from the `xml2rfc` SVN repository)
5. Then run “make” to create `xml2rfc-bibxml.{svn,fo,map}` etc.

**Comment by ronaldtse** [comment]
@HassanAkbar I've updated the README to provide more detail on how to author these scripts.

**Comment by HassanAkbar** [comment]
@ronaldtse I think the duplicates without the dot are due to some automated tasks that are creating commits with less then one second difference. Attaching some images for reference.

<img width="954" alt="Screenshot 2021-09-29 at 7 49 30 PM" src="https://user-images.githubusercontent.com/5301572/135295940-1749e015-a849-4eea-8264-373d74b0b9bc.png">
<img width="615" alt="Screenshot 2021-09-29 at 8 01 27 PM" src="https://user-images.githubusercontent.com/5301572/135295958-fd0f9cca-efa2-45c2-a1dd-4f79e7349dd1.png">

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar so the ones with '.' are actually separate commits but only have the added period due to the timestamp being identical. In Git they are separate commits.

In any case, the urgent matter is to resolve the SVN references within the commits into Git commit hashes.

**Comment by HassanAkbar** [comment]
@ronaldtse 
To make the `revision <=> git commit` mapping I was thinking about adding an option in tractive which will take the following input
- `.fo` file from reposurgeon
- A file containing the output of `git log --format='%cd!%ce %H %h %s' --date=format:%Y-%m-%dT%H:%M:%SZ` command
- A file containing the output of `svn log` command

What do you suggest? Should we add this in tractive or write a script to do this and in tractive ask the user to input the revamp file?

**Comment by ronaldtse** [comment]
@HassanAkbar we can actually generate the SVN to Git revision map this way.

`reposurgeon` by default inserts the "stamp" (e.g. `'2018-03-01T14:48:02Z!henrik@levkowetz.com'`) into every Git commit.

Given the pattern of the `.fo` file like this:
```
SVN:62	2018-02-21T16:11:31Z!henrik@levkowetz.com
```

1. Follow the instructions here (http://www.catb.org/~esr/reposurgeon/repository-editing.html#reference-lifting) to insert these Git aliases to your `~/.gitconfig`.

```
[alias]
	# git stamp <commit-ish> - print a reposurgeon-style action stamp
	stamp = show -s --format='%cI!%ce'

	# git scommit <stamp> <rev-list-args> - list most recent commit that matches <stamp>.
	# Must also specify a branch to search or --all, after these arguments.
	scommit = "!f(){ d=${1%%!*}; a=${1##*!}; arg=\"--until=$d -1\"; if [ $a != $1 ]; then arg=\"$arg --committer=$a\"; fi; shift; git rev-list $arg ${1:+\"$@\"}; }; f"

	# git scommits <stamp> <rev-list-args> - as above, but list all matching commits.
	scommits = "!f(){ d=${1%%!*}; a=${1##*!}; arg=\"--until=$d --after $d\"; if [ $a != $1 ]; then arg=\"$arg --committer=$a\"; fi; shift; git rev-list $arg ${1:+\"$@\"}; }; f"

	# git smaster <stamp> - list most recent commit on master that matches <stamp>.
	smaster = "!f(){ git scommit \"$1\" master --first-parent; }; f"
	smasters = "!f(){ git scommits \"$1\" master --first-parent; }; f"

	# git shs <stamp> - show the commits on master that match <stamp>.
	shs = "!f(){ stamp=$(git smasters $1); shift; git show ${stamp:?not found} $*; }; f"

	# git slog <stamp> <log-args> - start git log at <stamp> on master
	slog = "!f(){ stamp=$(git smaster $1); shift; git log ${stamp:?not found} $*; }; f"

	# git sco <stamp> - check out most recent commit on master that matches <stamp>.
	sco = "!f(){ stamp=$(git smaster $1); shift; git checkout ${stamp:?not found} $*; }; f"
```

2. Run the following command to find out the git commit hash of a particular SVN revision, e.g. 

(this example is from postconfirm)
```sh
$ git scommit '2018-02-21T16:11:31Z!henrik@levkowetz.com' --all
320d9a71e78a1ff0c1f86db60cad5370fb2a8674
```

**Comment by HassanAkbar** [comment]
@ronaldtse 
We can do it in Reposurgeon.
To make sure we are on the same page where should we add this logic of mapping? 
In the `reposurgeon make file` or would this be a manual operation which has to be done by the person converting the repo?

I've looked at the `scommit` and `scommits`. We can't use `scommit` in case of same timestamp & same user. We can rely on  `scommits` in that case.
For example, both `SVN:14` and `SVN:15` have same timestamps & users i.e. `2018-02-26T12:56:25Z!henrik@levkowetz.com`

When I ran `git scommits '2018-02-26T12:56:25Z!henrik@levkowetz.com' --all` the output was
> feaa472d319ba3cc26cc6e51aa7b31da0ee14365
> f39c50d2311ba1ae4e86979eff66d757ee4f091d

What I think we can do is sort the output and then map them:

```bash
1. SVN:14 ->  feaa472d319ba3cc26cc6e51aa7b31da0ee14365
2. SVN:15 ->  f39c50d2311ba1ae4e86979eff66d757ee4f091d
```
Hopefully, this will yield correct result but I am not sure if relying on the sorting will always yield 100% correct results.

**Comment by HassanAkbar** [comment]
> Occasionally (and usually by mistake) a branchy Subversion repository will contain revisions that touch multiple branches. These are handled by partitioning them into multiple import-stream commits, one on each affected branch. The Legacy-ID of such a split commit will have a pseudo-decimal part - for example, if Subversion revision 2317 touches three branches, the three generated commits will have IDs 2317.1, 2317.2, and 2317.3.

I've read this in the reposurgeon documentation. So I am confident we can ignore this.

**Comment by ronaldtse** [comment]
> What I think we can do is sort the output and then map them:
> Hopefully, this will yield correct result but I am not sure if relying on the sorting will always yield 100% correct results.

I think by "sorting" you mean the git commit tree linking these two commits together, that one is after the other?

Among all of these, we ignore all but one, because in Git these are 4 commits, but there is only one SVN revision:
```
SVN:49.1	2018-02-15T17:53:15Z!henrik@levkowetz.com
SVN:49.2	2018-02-15T17:53:15Z!henrik@levkowetz.com:2
SVN:49.4	2018-02-15T17:53:15Z!henrik@levkowetz.com:3
SVN:49.6	2018-02-15T17:53:15Z!henrik@levkowetz.com:4
```

Here 34.2 cannot be ignored even though it has a 'dot':
```
SVN:32	2017-10-11T16:18:49Z!henrik@levkowetz.com
SVN:33	2018-02-14T15:11:43Z!henrik@levkowetz.com
SVN:34.2	2018-02-14T15:26:29Z!henrik@levkowetz.com
SVN:37	2018-02-14T15:37:41Z!henrik@levkowetz.com
```

And SVN revisions 73, 74 must be separately mapped:
```
SVN:72	2018-04-20T11:51:23Z!henrik@levkowetz.com
SVN:73	2018-04-20T12:04:49Z!henrik@levkowetz.com
SVN:74	2018-04-20T12:04:49Z!henrik@levkowetz.com:2
SVN:76	2018-05-09T21:03:26Z!henrik@levkowetz.com
```

This is how I see 73 and 74 linked in Git:
```
$ git scommits '2018-04-20T12:04:49Z!henrik@levkowetz.com' --all
d2bbc3f16145a8ea51d228256c685c519a4294ac
7ef97a4feb5781dbc7adc1036f1e032f8f989f9f
$ git log d2bbc3f16145a8ea51d228256c685c519a4294ac --pretty=oneline
d2bbc3f16145a8ea51d228256c685c519a4294ac (tag: 0.41.5) Changelog entry for 0.41.5
7ef97a4feb5781dbc7adc1036f1e032f8f989f9f Set version info to release version 0.41.5 before tagging.
```

I wonder whether if there is another mechanism to do this mapping. It is frustrating that `reposurgeon` does not have a command that gives this mapping (`scommits` provides a listing that is ambiguous to work with).

**Comment by HassanAkbar** [comment]
@ronaldtse I think we can write a custom script to map `svn revisions` to `git sha hashes`, we can easily handle all of these cases inside that script. This will give us a lot of control over this mapping.
We can run it `after the reposurgeon` or `inside of tractive`.

**Comment by ronaldtse** [comment]
Yes we can also bundle this script in Tractive. I just don’t know whether we can actually the identically timed SVN Revisions to their corresponding commits using scommits. Maybe this is doable using raw Git or we can ask this question to reposurgeon’s gitlab.

**Comment by HassanAkbar** [comment]
@ronaldtse For the revisions having same timestamp & user, I think we can should compare the `git commit` and `svn revision` message.
The message comparison will only be needed in this case.

For that we can take the `git` and `svn` url from the user as an input and then use `svn log` and `git log` to get commit messages for the same timestamps & user.

In worst case scenario, if there is more than one revision with same `Timestamp`, `User` and `Revision Message`, then we can print/log all those cases to be analyzed manually.

**Comment by ronaldtse** [comment]
@HassanAkbar good idea on message comparison! Will let you handle this. Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse 
While working on the above-discussed approach، I came across a scenario where a `SHA` hash of git is not accessible from the `main` branch. [Here](https://github.com/ietf-ribose/ietfdb/commit/3ae26f540fac4ca233c2d87de47caa767b034a5c) is the commit for this SHA but it is not returned if we start searching from `main` branch.

<img width="475" alt="Screenshot 2021-10-05 at 7 41 48 PM" src="https://user-images.githubusercontent.com/5301572/136045702-560db9ba-35e9-4e61-a808-8cdf02e251e0.png">

However, this SHA is accessible If I try to go it it directly by doing `gitk 3ae26f540fac4ca233c2d87de47caa767b034a5c`. Feels like this SHA exists in a totally different tree but I am not 100% sure on this.

<img width="591" alt="Screenshot 2021-10-05 at 7 42 39 PM" src="https://user-images.githubusercontent.com/5301572/136045718-958e129e-e8c3-4fb4-8d70-c52bed81b165.png">

Importantly, I am using [Github Commits API](https://docs.github.com/en/rest/reference/repos#commits) for getting `commit messages` to compare for a duplicate commit which also does not returns this `commit`.

For example:

For the following revisions only one commit is returned from GitHub API. But 5 commits are returned from `scommits` with `--all` flag.
> SVN:728.1 2007-06-28T01:00:05Z!henrik@levkowetz.com
> SVN:728.2 2007-06-28T01:00:05Z!henrik@levkowetz.com:2
> SVN:728.3 2007-06-28T01:00:05Z!henrik@levkowetz.com:3
> SVN:729 2007-06-28T01:00:05Z!henrik@levkowetz.com:4

It feels like this is because Github API searches for the commit starting from `main branch`. We can change the head of searching to another branch but this will be extremely costly because we will have to search in every single branch to find this commit (Not sure if this approach is scalable especially for ietfdb).

What do you think about it?

**Comment by ronaldtse** [comment]
There are many commits that cannot be accessed via main as they are in unmerged branches. However, all of these commits can be accessed via GitHub.com. 

What are we exactly trying to do here? All we need is to replace the SVN revision in text (description in a commit message or issue comment) with the corresponding commit SHA. GitHub knows to make them into links. 

Also, the user must have a local copy of the git repo in order to run the SVN to Git mapping script.
