### ISSUE TITLE
Searching for tickets by track ticket #

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/svn-github-convert#40]
In the first run through the datatracker ticket->issue conversion, ticket #s and issue #s were lining up - was that coincidence or will that be the case in the final transition?

I note that we can search for e.g. 'from trac:3261' successfully, but not 'from trac:22'
That won't matter if the #s are 1-1, but if they aren't...

**Comment by ronaldtse** [comment]
@rjsparks this is an intentional feature. Any gaps in numbering on the Trac side will trigger creation of a dummy ticket in order to align the numbers. It’s a feature that can be disabled (see README of Tractive).
