### ISSUE TITLE
Migrating deleted branches?

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#41]
@rjsparks should we migrate deleted branches from SVN? The SVN repository could contain branches that are deleted but still present.

**Comment by rjsparks** [comment]
To the extent feasible, we should preserve the history of the code. We should be able to look where code came from.

Off the top of my head, there are very few truly deleted branches in the ietfdb project - there are instances of a practice of moving branches into the /attic top level directory of the project.

What have you run across that triggered the question?

**Comment by ronaldtse** [comment]
This just came to mind when I realised that the server side SVN repository could contain deleted branches. I did not check whether the SVN repositories right now contain those. Reposurgon does provide an option to preserve deleted SVN branches for completeness reasons.

**Comment by ronaldtse** [comment]
All done, closing.
