### ISSUE TITLE
Confirm format of migrated Git commit

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#43]
@rjsparks could you help verify that the conversion here makes sense? Thanks.

https://github.com/hassanakbar4/ietfdb-filter-repo-test/commit/02fa573c26bab915cca98f1f222adba3ade88fec

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/svn-github-convert/issues/18#issuecomment-972534331_

**Comment by rjsparks** [comment]
Yes - the format of the ticket looks fine.

(I have a question about the final integration of the tickets and the code repository - in this test repository, at least, when looking at the commits the ticket points to, they warn "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."?)

**Comment by ronaldtse** [comment]
All done, this is closing.
