### ISSUE TITLE
Attachment linkage and rendering

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/svn-github-convert#46]
https://github.com/ietf-svn-conversion/mailarchive/issues/3178

<img width="921" alt="Screenshot 2021-11-23 at 3 30 22 PM" src="https://user-images.githubusercontent.com/11865/142985325-f81d5b84-6646-4ab3-8f72-d87788b7b044.png">

This issue shows a broken attachment link, and also unable to display it.

1. The link of `mailarchive-list-info-mockup.png` goes to: `https://abc.com/raw-attachment/ticket/3178/mailarchive-list-info-mockup.png`

2. The linked image goes to `https://camo.githubusercontent.com/73dfaca0240636bc432edd74091fafb5703a70ac2fd67e0bcb933322557729f0/68747470733a2f2f6162632e636f6d2f7261772d6174746163686d656e742f7469636b65742f333137382f6d61696c617263686976652d6c6973742d696e666f2d6d6f636b75702e706e67`

**Comment by ronaldtse** [comment]
Is this a Tractive issue or a configuration / migration issue?

**Comment by HassanAkbar** [comment]
@ronaldtse This is a configuration issue.
Instead of abc.com, we need to add the actual host domain where attachments are available.
Can we get it from IETF team if you don’t have these available already ?

**Comment by ronaldtse** [comment]
I thought we agreed to migrate all the attachments into a separate GitHub repository? We can link to those attachments there.

**Comment by HassanAkbar** [comment]
@ronaldtse Actually, only file names are available in Database. I am hoping we will be able to generate complete URL by doing #{HOST}/#{FileName}.
So, we need the HOST for downloading the images and then we need to upload them to the GitHub.

**Comment by ronaldtse** [comment]
@rjsparks it seems that in the Trac db rsync we have there is only one attachment:

<img width="233" alt="image" src="https://user-images.githubusercontent.com/11865/143524685-f9d30cdb-d0ef-4dd9-b5d9-3e878d8f329a.png">

Could we either rsync the other attachments, or use some endpoint to retrieve them to upload to GitHub for the migration?

**Comment by ronaldtse** [comment]
The file attachments are actually inside `ietf-ribose/trac-svn-convert`, at:

(Tickets)
<img width="398" alt="Screenshot 2021-11-26 at 12 01 11 PM" src="https://user-images.githubusercontent.com/11865/143524927-7dedeb35-4a17-4c69-90a1-00b619576016.png">

and

(Wiki):
<img width="398" alt="Screenshot 2021-11-26 at 12 01 33 PM" src="https://user-images.githubusercontent.com/11865/143524951-b6d34780-d8aa-4805-aa18-297b1ba6c8d2.png">

**Comment by HassanAkbar** [comment]
@ronaldtse I think I don't have access to `ietf-ribose/trac-svn-convert`.

**Comment by ronaldtse** [comment]
@HassanAkbar you should already do...?
<img width="279" alt="Screenshot 2021-11-26 at 3 35 09 PM" src="https://user-images.githubusercontent.com/11865/143543881-c89f015f-3ce1-41ca-b42d-33aa418db4da.png">

**Comment by HassanAkbar** [comment]
@ronaldtse I was looking for `ietf-ribose/trac-svn-convert`.
Found [ietf-ribose/trac-svn-db](https://github.com/ietf-ribose/trac-svn-db) and data required in there.
Thanks for clarification.

**Comment by ronaldtse** [comment]
No problem @HassanAkbar !

**Comment by HassanAkbar** [comment]
@ronaldtse Do we know how to convert the FileName from trac attachments to the FileName in [ietf-ribose/trac-svn-db](https://github.com/ietf-ribose/trac-svn-db) repo (looks like some kind of encoding here) ?
Otherwise I can do some research on this.

<img width="398" alt="143524951-b6d34780-d8aa-4805-aa18-297b1ba6c8d2" src="https://user-images.githubusercontent.com/5301572/143570699-ecd536c8-d185-44c0-a6a5-19166ad42f50.png">

**Comment by HassanAkbar** [comment]
> @rjsparks ~it seems that in the Trac db rsync we have there is only one attachment:~
> 
> <img alt="image" width="233" src="https://user-images.githubusercontent.com/11865/143524685-f9d30cdb-d0ef-4dd9-b5d9-3e878d8f329a.png">
> 
> ~Could we either rsync the other attachments, or use some endpoint to retrieve them to upload to GitHub for the migration?~
> 
> UPDATE: Found them.

@ronaldtse if we can have this kind of structure (as shown in the above image) for exported images. It will be really easy to export and map images.
Tractive also provides a functionality to export images in this structure. Once we have exported images in this format we can import that to a repo smoothly.

**Comment by ronaldtse** [comment]
> if we can have this kind of structure (as shown in the above image) for exported images. It will be really easy to export and map images.

Got it. Is there anything you need me to do?

**Comment by HassanAkbar** [comment]
@ronaldtse I'm looking into the trac source code to figure out how the names of the images/directories are converted.

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar
