### ISSUE TITLE
Non standard formatting in Wikis

### ISSUE THREAD

**Issue by HassanAkbar** [ietf-ribose/svn-github-convert#56]
Some Wikis have attachments mentioned that are not in a [standard format](https://trac.edgewall.org/wiki/WikiFormatting).
For example,
- `attachment:Screen%20Shot%202018-04-09%20at%2015.18.23.png` in [EditingSandBox@ietfdb](https://github.com/ietf-svn-conversion/ietfdb/wiki/EditingSandBox)
- `[/tools/ietfdb/attachment/wiki/Model/models.pdf?format=raw models.pdf]` in [Model@ietfdb](https://github.com/ietf-svn-conversion/ietfdb/wiki/Model)

And some Wikis don’t reference the attachments in the description at all.

@rjsparks What should we do in these cases ?
Should we just update the `tractive` to add a heading named `Attachments` at the end of the description and add links to all attachments there ?

cc: @ronaldtse

**Comment by ronaldtse** [comment]
Agree!

**Comment by HassanAkbar** [comment]
Fixed in https://github.com/ietf-ribose/tractive/pull/72
