### ISSUE TITLE
Git filter repo issue

### ISSUE THREAD

**Issue by HassanAkbar** [ietf-ribose/svn-github-convert#57]
@ronaldtse Git filter repo is processing a few commits in reverse order.
For example:
1. https://github.com/ietf-svn-conversion/xml2rfc/commit/fe3850a43adfa560407abada322d650fc711f1e0 is added on `28 Oct`
2. https://github.com/ietf-svn-conversion/xml2rfc/commit/a327c32e45604d265fa3adf87ed37d7e6ba14151 is added on `29 Oct`

but (2) is getting processed before (1) 

This causes an issue in references, i.e
- https://github.com/ietf-svn-conversion/xml2rfc/commit/a327c32e45604d265fa3adf87ed37d7e6ba14151 should point to https://github.com/ietf-svn-conversion/xml2rfc/commit/fe3850a43adfa560407abada322d650fc711f1e0 but it is pointing to https://github.com/ietf-svn-conversion/xml2rfc/commit/018842d9a4893b4347d8a2b510c1bd78aac95d61, which is an old commit,

This is happening because commit (2) is getting processed before commit (1) so it is referring to the `old SHA` of commit (1) because `new SHA` is not available at this point and will be generated when (1) is processed.

Each commit is processed only once so the new reference of commit (1) is never added in commit (2).

**Comment by ronaldtse** [comment]
The other tool I know that does reliable editing of Git repos is BFG, but it does not deal with commit hash rewriting...

**Comment by HassanAkbar** [comment]
> The other tool I know that does reliable editing of Git repos is BFG, but it does not deal with commit hash rewriting...

@ronaldtse
Let me try to go into the code `git-filter-repo`and debug why it's failing in this specific case.
In the worst case, do you think using some URL shortener service (this can be self-hosted too) is an option or do you think we should we should stay away from external dependencies?

**Comment by ronaldtse** [comment]
@HassanAkbar 

> In the worst case, do you think using some URL shortener service (this can be self-hosted too) is an option or do you think we should we should stay away from external dependencies?

We hope to stay away from external dependencies if possible.

It is possible for us to just offer a static/JS site that does that SVN revision to Git hash conversion...

I wonder if we can fix `git-filter-repo` to provide the correct order? It seems like a bug on their side.

**Comment by HassanAkbar** [comment]
@ronaldtse I've updated the `git-filter-repo` and added a flag to `sort` the commits by date. I pushed the change in the [forked `git-filter-repo` branch](https://github.com/riboseinc/git-filter-repo/tree/changing_order_of_msg_update) and used that branch in the workflows. So everything seems to be working fine now.

**Comment by HassanAkbar** [comment]
Issue is fixed by using the [forked `git-filter-repo` branch](https://github.com/riboseinc/git-filter-repo/tree/changing_order_of_msg_update) and using that in the [workflow](https://github.com/ietf-ribose/svn-github-convert/blob/c95e90282ccc3394302ab8f4010edcc22ac01f25/.github/workflows/convert.yml#L191).
