### ISSUE TITLE
XML tags in plain text are missing from imported issues

### ISSUE THREAD

**Issue by kesara** [ietf-ribose/svn-github-convert#68]
Track issue: https://trac.ietf.org/trac/ietfdb/ticket/3451
Github issue: https://github.com/ietf-tools/datatracker/issues/3451

Source code tags are missing in both the main issue and comment.
Not sure, this is an isolated case.

**Comment by kesara** [comment]
Looks like if trac issue has XML/HTML tags and they are wrapped by proper code styling, imported issues are okay.
But whenever trac issue's XML/HTML tagss are not wrapped with proper styling, imported issues can be unpredictable.
Another example:
trac: https://trac.ietf.org/trac/ietfdb/ticket/3466
github: https://github.com/ietf-tools/datatracker/issues/3466

**Comment by rjsparks** [comment]
I'm leaning towards wontfix for this one. Where it matters, we can manually correct the issue.
Fwiw, I think the tags are there if you edit the comment - you just have to add styling to make them render correctly on github.

**Comment by ronaldtse** [comment]
Thanks @rjsparks ! Then let's close this for now.
